apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-sql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azuresql
  template:
    metadata:
      name: azuresql-db
      labels:
        app: azuresql
    spec:
      containers:
        - name: azure-sql-db
          image: mcr.microsoft.com/azure-sql-edge 
          ports:
            - containerPort: 1433 
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
            - name: SA_PASSWORD
              value: "8jkGh47hnDw89Haq8LN2"  
          volumeMounts:
            - name: sqlserverdata
              mountPath: /var/opt/mssql
      volumes:
        - name: sqlserverdata
          persistentVolumeClaim:
            claimName: sqlserverdata-pvc    