apiVersion: v1
kind: Service
metadata:
  name: customermanagementapi-service
spec:
  selector:
    app: customermanagementapi
  ports:
    - name: http
      port: 80  
      targetPort: 5100  
  type: ClusterIP  
