apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: pitstop/webapp:1.0
          ports:
            - containerPort: 7005 
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          
