apiVersion: v1
kind: Service
metadata:
  name: workshopmanagementapi-service
spec:
  selector:
    app: workshopmanagementapi
  ports:
    - name: http
      port: 80  
      targetPort: 5000  
  type: ClusterIP  
